### ISSUE TITLE
Add amd64 build

### ISSUE THREAD

**Issue by dgzlopes** [kamranahmedse/local-ses#3]
Right now, the Docker image provided doesn't work on amd64 machines:
```
➜  local-ses git:(main) ✗ docker run -it -p 8285:8282 kamranahmed/local-ses
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

The image [could be built](https://docs.docker.com/build/building/multi-platform/) to support this.

**Comment by dgzlopes** [comment]
For now, I have built it locally, at it is working flawlessly :+1:

**Comment by nilbuild** [comment]
Fixed in https://github.com/kamranahmedse/local-ses/commit/85f86c52cdc597429a150d6a8da985e66886127c. Thank you!
